/**
 * @fileoverview NotebookLM consultation tool — the shared core that all
 * NotebookLM-related agents and API routes delegate to.
 *
 * Flow:
 *  1. Build an authenticated `NotebookLMClient` using Browser Rendering to
 *     fetch the CSRF token with a real Chrome User-Agent.
 *  2. Read `agent_rules` from the `global_config` D1 table.
 *  3. Prepend the rules to the user's query so NotebookLM always follows
 *     the configured behavioral constraints.
 *  4. Call `client.chat.ask(notebookId, guardedQuery)` and return the result.
 *
 * Credential layout:
 *  - KV `ACTIVE_NOTEBOOKLM_SESSION`  → session cookies (hot-swap)
 *  - `CAREER_NOTEBOOKLM_ID`          → env var (notebook identifier)
 *
 * CSRF token discovery:
 *  Uses Browser Rendering `/content` with a Chrome User-Agent instead of the
 *  SDK's bare `fetch()` which was detected as non-browser by Google and
 *  shortened session lifetime from ~30 days to ~1 hour.
 *
 *  The auth object (CSRF token, session ID) is cached in KV with a
 *  sliding-window TTL — active usage refreshes the TTL, idle periods
 *  let it expire naturally so the next call re-fetches fresh.
 */

import { eq } from "drizzle-orm";
import { NotebookLMClient, type AskResult } from "notebooklm-sdk";

import { getDb } from "@/backend/db";
import { globalConfig } from "@/backend/db/schema";
import { getNotebookLMCookies } from "@/backend/utils/secrets";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CHROME_USER_AGENT =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36";

const NOTEBOOKLM_URL = "https://notebooklm.google.com/";

/** KV key for the cached auth object (sliding-window TTL). */
const CSRF_CACHE_KEY = "NOTEBOOKLM_CSRF_CACHE";

/** Sliding window TTL in seconds — active usage refreshes this. */
const CSRF_CACHE_TTL_SECONDS = 30 * 60; // 30 minutes

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * The shape returned by {@link consultNotebook} and consumed by both the
 * `/api/notebook/chat` route and the `NotebookLMAgent` Durable Object.
 */
export type NotebookConsultation = {
  /** The answer text generated by NotebookLM. */
  answer: string;
  /** Conversation identifier for multi-turn tracking. */
  conversationId: string;
  /** Sequential turn number within the conversation. */
  turnNumber: number;
  /** Source references cited in the answer. */
  references: AskResult["references"];
};

/**
 * Error thrown when NotebookLM session cookies are expired or invalid.
 * The `recoveryCommand` property contains the exact CLI command to fix it.
 */
export class SessionExpiredError extends Error {
  public readonly recoveryCommand: string;

  constructor(cause?: unknown) {
    super("SESSION_EXPIRED: NotebookLM session cookies are expired or invalid.");
    this.name = "SessionExpiredError";
    this.recoveryCommand = "pnpm run session:sync";
    if (cause) this.cause = cause;
  }
}

// ---------------------------------------------------------------------------
// Cached auth type
// ---------------------------------------------------------------------------

/** Shape stored in KV for the cached CSRF auth object. */
type CachedAuth = {
  csrfToken: string;
  sessionId: string;
  cookieHeader: string;
  /** ISO timestamp of when this auth was fetched. */
  fetchedAt: string;
};

// ---------------------------------------------------------------------------
// Primary public function
// ---------------------------------------------------------------------------

/**
 * Send a query to the NotebookLM career knowledge base.
 *
 * Agent rules from D1 are prepended to every query so the model always
 * operates within the configured guardrails.
 *
 * @param env - Cloudflare Worker environment bindings.
 * @param query - Natural-language question from the user or an agent.
 * @returns A {@link NotebookConsultation} with the answer, conversation context,
 *          and source references.
 * @throws {SessionExpiredError} if the SDK fails due to expired session cookies.
 */
export async function consultNotebook(env: Env, query: string): Promise<NotebookConsultation> {
  const [client, notebookId, rules] = await Promise.all([
    createNotebookClient(env),
    env.CAREER_NOTEBOOKLM_ID,
    readAgentRules(env),
  ]);
  const guardedQuery = withAgentRules(query, rules);

  try {
    const result = await client.chat.ask(notebookId, guardedQuery);

    return {
      answer: result.answer,
      conversationId: result.conversationId,
      turnNumber: result.turnNumber,
      references: result.references,
    };
  } catch (error) {
    // Detect auth-related failures and wrap with actionable recovery info
    if (isAuthError(error)) {
      // Invalidate CSRF cache on auth failure so next call re-fetches
      try {
        await env.KV.delete(CSRF_CACHE_KEY);
      } catch {
        // Non-fatal — ignore KV delete failures
      }
      throw new SessionExpiredError(error);
    }
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Internal helpers — CSRF Token via Browser Rendering
// ---------------------------------------------------------------------------

/**
 * Extract CSRF token (`SNlM0e`) from NotebookLM page HTML.
 * Uses the same regex pattern as the notebooklm-sdk.
 */
function extractCsrfToken(html: string): string {
  const match = /"SNlM0e"\s*:\s*"([^"]+)"/.exec(html);
  if (!match?.[1]) {
    if (html.includes("accounts.google.com")) {
      throw new SessionExpiredError("Redirected to Google login — cookies expired");
    }
    throw new Error("CSRF token (SNlM0e) not found in NotebookLM page HTML");
  }
  return match[1];
}

/**
 * Extract session ID (`FdrFJe`) from NotebookLM page HTML.
 * Uses the same regex pattern as the notebooklm-sdk.
 */
function extractSessionId(html: string): string {
  const match = /"FdrFJe"\s*:\s*"([^"]+)"/.exec(html);
  if (!match?.[1]) {
    if (html.includes("accounts.google.com")) {
      throw new SessionExpiredError("Redirected to Google login — cookies expired");
    }
    throw new Error("Session ID (FdrFJe) not found in NotebookLM page HTML");
  }
  return match[1];
}

/**
 * Parse a cookie string into an array of `{ name, value, domain }` objects
 * suitable for the Browser Rendering API `cookies` parameter.
 */
function parseCookiesForBrowser(
  cookieStr: string,
): Array<{ name: string; value: string; url: string; domain: string; path: string }> {
  const cookies: Array<{ name: string; value: string; url: string; domain: string; path: string }> = [];

  for (const part of cookieStr.split(/;\s*/)) {
    const idx = part.indexOf("=");
    if (idx > 0) {
      const name = part.slice(0, idx).trim();
      const value = part.slice(idx + 1).trim();
      if (name) {
        cookies.push({
          name,
          value,
          url: "https://notebooklm.google.com",
          domain: ".google.com",
          path: "/",
        });
      }
    }
  }

  return cookies;
}

/**
 * Fetch CSRF token and session ID from the NotebookLM page using
 * Browser Rendering `/content` endpoint with a real Chrome User-Agent.
 *
 * This replaces the SDK's bare `fetch()` which used a Cloudflare Worker
 * edge IP and no User-Agent, causing Google to shorten session lifetime.
 */
async function fetchCsrfViaBrowser(env: Env, cookieString: string): Promise<CachedAuth> {
  const accountId = await env.CLOUDFLARE_ACCOUNT_ID.get();
  const token = await env.CF_BROWSER_RENDER_TOKEN.get();

  const browserCookies = parseCookiesForBrowser(cookieString);

  const response = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${accountId}/browser-rendering/content`,
    {
      method: "POST",
      headers: {
        authorization: `Bearer ${token}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        url: NOTEBOOKLM_URL,
        cookies: browserCookies,
        userAgent: CHROME_USER_AGENT,
        gotoOptions: { waitUntil: "domcontentloaded" },
        // Block unnecessary resources to speed up the page load
        rejectResourceTypes: ["image", "stylesheet", "font", "media"],
      }),
    },
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Browser Rendering /content failed for CSRF fetch: ${response.status} ${errorText.slice(0, 300)}`,
    );
  }

  const payload = (await response.json()) as { success: boolean; result: string };
  const html = payload.result;

  if (!html || html.length < 100) {
    throw new Error(
      `Browser Rendering returned empty/short HTML for NotebookLM (${html?.length ?? 0} chars)`,
    );
  }

  // Check for Google auth redirect in the rendered HTML
  if (
    html.includes("accounts.google.com/signin") ||
    html.includes("accounts.google.com/v3/signin")
  ) {
    throw new SessionExpiredError("NotebookLM page redirected to Google sign-in — cookies expired");
  }

  const csrfToken = extractCsrfToken(html);
  const sessionId = extractSessionId(html);

  return {
    csrfToken,
    sessionId,
    cookieHeader: cookieString,
    fetchedAt: new Date().toISOString(),
  };
}

/**
 * Get or create a cached CSRF auth object with sliding-window TTL.
 *
 * - If cached auth exists in KV: use it and refresh the TTL (sliding window)
 * - If missing/expired: fetch fresh via Browser Rendering and cache
 */
async function getOrFetchAuth(env: Env, cookieString: string): Promise<CachedAuth> {
  // Try reading cached auth from KV
  try {
    const cached = await env.KV.get(CSRF_CACHE_KEY);
    if (cached) {
      const auth = JSON.parse(cached) as CachedAuth;

      // Verify the cached auth was built from the same cookies
      // (if cookies were rotated, the cache is stale)
      if (auth.cookieHeader === cookieString) {
        // Sliding window: refresh the TTL on every active use
        await env.KV.put(CSRF_CACHE_KEY, cached, {
          expirationTtl: CSRF_CACHE_TTL_SECONDS,
        });
        return auth;
      }

      // Cookie mismatch — delete stale cache and fetch fresh
      await env.KV.delete(CSRF_CACHE_KEY);
    }
  } catch {
    // KV read failed — proceed to fetch
  }

  // Cache miss or stale — fetch fresh via Browser Rendering
  const auth = await fetchCsrfViaBrowser(env, cookieString);

  // Cache with sliding window TTL
  try {
    await env.KV.put(CSRF_CACHE_KEY, JSON.stringify(auth), {
      expirationTtl: CSRF_CACHE_TTL_SECONDS,
    });
  } catch {
    // Non-fatal — caching failure shouldn't block the operation
  }

  return auth;
}

// ---------------------------------------------------------------------------
// Client construction
// ---------------------------------------------------------------------------

/**
 * Construct an authenticated {@link NotebookLMClient} by bypassing the
 * SDK's `connect()` method and building the auth object ourselves.
 *
 * Flow:
 *   1. Read session cookies from KV
 *   2. Get or fetch CSRF token (cached with sliding-window TTL)
 *   3. Construct `NotebookLMClient` directly with pre-built auth
 *
 * This eliminates the SDK's bare `fetch()` to notebooklm.google.com which
 * was detected as non-browser access by Google.
 */
export async function createNotebookClient(env: Env): Promise<NotebookLMClient> {
  const cookieString = await getNotebookLMCookies(env);

  if (!cookieString || cookieString.length < 10) {
    throw new Error(
      "NotebookLM session cookies not found. " +
        "Update from Config → NotebookLM Session, or run: pnpm run session:sync",
    );
  }

  const auth = await getOrFetchAuth(env, cookieString);

  // Build the auth object that NotebookLMClient constructor expects
  // This mirrors what the SDK's connect() function returns
  const cookieMap: Record<string, string> = {};
  for (const part of cookieString.split(/;\s*/)) {
    const idx = part.indexOf("=");
    if (idx > 0) {
      const name = part.slice(0, idx).trim();
      const value = part.slice(idx + 1).trim();
      if (name) cookieMap[name] = value;
    }
  }

  const sdkAuth = {
    cookies: cookieMap,
    csrfToken: auth.csrfToken,
    sessionId: auth.sessionId,
    cookieHeader: auth.cookieHeader,
    googleCookieHeader: auth.cookieHeader,
  };

  // @ts-expect-error — NotebookLMClient constructor is private but we need to
  // bypass connect() which uses a bare fetch() that triggers Google bot detection.
  // Our auth object is built from Browser Rendering with a Chrome User-Agent.
  return new NotebookLMClient(sdkAuth, { timeoutMs: 30_000 });
}

// ---------------------------------------------------------------------------
// Agent rules
// ---------------------------------------------------------------------------

/**
 * Read the `agent_rules` array from the `global_config` D1 table.
 *
 * These rules are editable via the `/config` UI and are prepended to every
 * NotebookLM query to enforce behavioral constraints.
 *
 * @returns An array of rule strings, or an empty array if none are configured.
 */
async function readAgentRules(env: Env): Promise<string[]> {
  const db = getDb(env);
  const [row] = await db
    .select({ value: globalConfig.value })
    .from(globalConfig)
    .where(eq(globalConfig.key, "agent_rules"))
    .limit(1);

  return Array.isArray(row?.value)
    ? row.value.filter((value): value is string => typeof value === "string")
    : [];
}

/**
 * Wrap a user query with agent rules.
 *
 * If rules are configured, they are formatted as a bullet list and prepended
 * to the query.  If no rules exist, the original query is returned unchanged.
 */
function withAgentRules(query: string, rules: string[]): string {
  if (rules.length === 0) {
    return query;
  }

  return `Follow these Career Orchestrator rules before answering:\n${rules.map((rule) => `- ${rule}`).join("\n")}\n\nUser query:\n${query}`;
}

/**
 * Detect whether an error from the NotebookLM SDK indicates expired
 * or invalid session cookies.
 *
 * Checks for:
 *  - SDK `AuthError` class name
 *  - Error messages containing login/auth/expired/CSRF keywords
 *  - Google sign-in redirect indicators
 */
export function isAuthError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;

  const err = error as Error;
  const name = err.name?.toLowerCase() ?? "";
  const msg = err.message?.toLowerCase() ?? "";

  if (name.includes("auth")) return true;
  if (msg.includes("expired")) return true;
  if (msg.includes("login")) return true;
  if (msg.includes("csrf")) return true;
  if (msg.includes("sign in")) return true;
  if (msg.includes("accounts.google.com")) return true;
  if (msg.includes("unauthorized")) return true;

  return false;
}

// ---------------------------------------------------------------------------
// Session availability check (used by agent healthProbe and health checks)
// ---------------------------------------------------------------------------

/** Result of a session availability check. */
export type SessionCheckResult = {
  available: boolean;
  source: "kv" | "none";
};

/**
 * Lightweight check for whether a valid NotebookLM session exists.
 *
 * Agents and health checks should use this instead of reading KV/secrets
 * directly. Reads from KV `ACTIVE_NOTEBOOKLM_SESSION` only — the Worker
 * Secret fallback has been removed.
 *
 * Does NOT validate the session against Google — only checks that a
 * non-trivial cookie string is present.
 */
export async function checkNotebookLMSession(env: Env): Promise<SessionCheckResult> {
  try {
    const kvSession = await env.KV.get("ACTIVE_NOTEBOOKLM_SESSION");
    if (kvSession && kvSession.trim().length > 10) {
      return { available: true, source: "kv" };
    }
  } catch (error) {
    throw new Error(
      `[checkNotebookLMSession] Failed to check session availability: ${String(error)}`,
    );
  }

  return { available: false, source: "none" };
}
